In [1]:
import pandas as pd

In [27]:
df = pd.read_csv('Online_Retail.csv')
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/10 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/10 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/10 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/10 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/10 8:26,3.39,17850.0,United Kingdom

In [27]:
df = pd.read_csv('Online_Retail.csv')
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/10 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/10 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/10 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/10 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/10 8:26,3.39,17850.0,United Kingdom

In [28]:
df["InvoiceMonth"] = pd.to_datetime(df["InvoiceDate"], format="%m/%d/%y %H:%M").dt.to_period("M").astype(str)

In [29]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,InvoiceMonth
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/10 8:26,2.55,17850.0,United Kingdom,2010-12
1,536365,71053,WHITE METAL LANTERN,6,12/1/10 8:26,3.39,17850.0,United Kingdom,2010-12
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/10 8:26,2.75,17850.0,United Kingdom,2010-12
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/10 8:26,3.39,17850.0,United Kingdom,2010-12
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/10 8:26,3.39,17850.0,United Kingdom,2010-12

In [34]:
df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"], format="%m/%d/%y %H:%M").dt.normalize()
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,InvoiceMonth
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01,2.55,17850.0,United Kingdom,2010-12
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01,3.39,17850.0,United Kingdom,2010-12
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01,2.75,17850.0,United Kingdom,2010-12
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01,3.39,17850.0,United Kingdom,2010-12
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01,3.39,17850.0,United Kingdom,2010-12

In [35]:
df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,InvoiceMonth
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01,2.55,17850.0,United Kingdom,2010-12
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01,3.39,17850.0,United Kingdom,2010-12
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01,2.75,17850.0,United Kingdom,2010-12
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01,3.39,17850.0,United Kingdom,2010-12
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01,3.39,17850.0,United Kingdom,2010-12
...,...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09,0.85,12680.0,France,2011-12
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09,2.10,12680.0,France,2011-12
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09,4.15,12680.0,France,2011-12
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09,4.15,12680.0,France,2011-12
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09,4.95,12680.0,France,2011-12

In [43]:
df.dropna().count()

InvoiceNo       401603
StockCode       401603
Description     401603
Quantity        401603
InvoiceDate     401603
UnitPrice       401603
CustomerID      401603
Country         401603
InvoiceMonth    401603
dtype: int64

In [44]:
df = df.drop_duplicates()
print(len(df))  # 401603 hona chahiye

536640

In [55]:
import pandas as pd

SRC = "Online_Retail.csv"
OUT = "OnlineRetail_clean.csv"

df = pd.read_csv(SRC, encoding="utf-8-sig", dtype={"InvoiceNo": str, "StockCode": str})
print("Raw:", len(df))

df["Description"] = df["Description"].str.strip().str.upper()
df["Country"] = df["Country"].str.strip()

df = df.drop_duplicates()
print("After duplicates:", len(df))

df = df.dropna(subset=["Description", "CustomerID"])
print("After blank desc/customer:", len(df))
df["CustomerID"] = df["CustomerID"].astype(int).astype(str)

df = df[~df["InvoiceNo"].str.startswith("C")]
print("After cancellations:", len(df))

df = df[(df["Quantity"] > 0) & (df["UnitPrice"] > 0)]
print("After qty/price:", len(df))

df = df[~df["StockCode"].isin(["POST", "M", "C2", "DOT", "BANK CHARGES", "PADS"])]
print("After non-product:", len(df))

df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"], format="%m/%d/%y %H:%M").dt.normalize()
df["Revenue"] = (df["Quantity"] * df["UnitPrice"]).round(2)
df["InvoiceMonth"] = df["InvoiceDate"].dt.to_period("M").astype(str)

print("Invoices:", df["InvoiceNo"].nunique())
print("Customers:", df["CustomerID"].nunique())
print("Total revenue:", round(df["Revenue"].sum(), 2))

df.to_csv(OUT, index=False, encoding="utf-8")
print("Saved:", OUT)

Raw: 541909
After duplicates: 536641
After blank desc/customer: 401604
After cancellations: 392732
After qty/price: 392692
After non-product: 391150
Invoices: 18402
Customers: 4334
Total revenue: 8737227.64
Saved: OnlineRetail_clean.csv

In [56]:
import os
print(os.path.abspath("OnlineRetail_clean.csv"))

C:\Users\KARAN\skyrovix  data analist\task 2\OnlineRetail_clean.csv