In [8]:
import pandas as pd

In [42]:
df = pd.read_csv('sales_data.csv')
df

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Price,Discount,Weather Condition,Promotion,Competitor Pricing,Seasonality,Epidemic,Demand
0,1/1/2022,S001,P0001,Electronics,North,195,102,252,72.72,5,Snowy,0,85.73,Winter,0,115
1,1/1/2022,S001,P0002,Clothing,North,117,117,249,80.16,15,Snowy,1,92.02,Winter,0,229
2,1/1/2022,S001,P0003,Clothing,North,247,114,612,62.94,10,Snowy,1,60.08,Winter,0,157
3,1/1/2022,S001,P0004,Electronics,North,139,45,102,87.63,10,Snowy,0,85.19,Winter,0,52
4,1/1/2022,S001,P0005,Groceries,North,152,65,271,54.41,0,Snowy,0,51.63,Winter,0,59
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75995,1/30/2024,S005,P0016,Toys,North,233,63,0,29.80,5,Snowy,0,32.23,Winter,0,64
75996,1/30/2024,S005,P0017,Toys,North,137,115,141,42.92,5,Snowy,0,40.73,Winter,0,137
75997,1/30/2024,S005,P0018,Clothing,North,197,44,0,17.81,10,Snowy,0,19.41,Winter,0,68
75998,1/30/2024,S005,P0019,Furniture,North,125,58,0,151.72,0,Snowy,0,143.71,Winter,0,84
75999,1/30/2024,S005,P0020,Toys,North,126,63,59,25.78,10,Snowy,0,29.32,Winter,0,73

In [47]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 76000 entries, 0 to 75999
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Date                76000 non-null  str
 1   Store ID            76000 non-null  str
 2   Product ID          76000 non-null  str
 3   Category            76000 non-null  str
 4   Region              76000 non-null  str
 5   Inventory Level     76000 non-null  int64
 6   Units Sold          76000 non-null  int64
 7   Units Ordered       76000 non-null  int64
 8   Price               76000 non-null  float64
 9   Discount            76000 non-null  int64
 10  Weather Condition   76000 non-null  str
 11  Promotion           76000 non-null  int64
 12  Competitor Pricing  76000 non-null  float64
 13  Seasonality         76000 non-null  str
 14  Epidemic            76000 non-null  int64
 15  Demand              76000 non-null  int64
 16  year                76000 non-null  int32
 17  month               76000 non-null  str
dtypes: float64(2), int32(1), int64(7), str(8)
memory usage: 13.7 MB

In [48]:
df.shape

(76000, 18)

In [43]:
df.isnull().sum()

Date                  0
Store ID              0
Product ID            0
Category              0
Region                0
Inventory Level       0
Units Sold            0
Units Ordered         0
Price                 0
Discount              0
Weather Condition     0
Promotion             0
Competitor Pricing    0
Seasonality           0
Epidemic              0
Demand                0
dtype: int64

In [54]:
df.nunique()

Date                    760
Store ID                  5
Product ID               20
Category                  5
Region                    4
Inventory Level        1426
Units Sold              330
Units Ordered           996
Price                 15396
Discount                  6
Weather Condition         4
Promotion                 2
Competitor Pricing    15963
Seasonality               4
Epidemic                  2
Demand                  340
year                      3
month                    12
dtype: int64

In [50]:
df.duplicated().sum()

np.int64(0)

In [53]:
df.describe()

,Inventory Level,Units Sold,Units Ordered,Price,Discount,Promotion,Competitor Pricing,Epidemic,Demand,year
count,76000.000000,76000.000000,76000.000000,76000.000000,76000.000000,76000.000000,76000.000000,76000.000000,76000.000000,76000.000000
mean,301.062842,88.827316,89.090645,67.726028,9.087039,0.328947,69.454029,0.200000,104.317158,2022.559211
std,226.510161,43.994525,162.404627,39.377899,7.475781,0.469834,40.943818,0.400003,46.964801,0.570479
min,0.000000,0.000000,0.000000,4.740000,0.000000,0.000000,4.290000,0.000000,4.000000,2022.000000
25%,136.000000,58.000000,0.000000,31.997500,5.000000,0.000000,32.620000,0.000000,71.000000,2022.000000
50%,227.000000,84.000000,0.000000,64.500000,10.000000,0.000000,65.700000,0.000000,100.000000,2023.000000
75%,408.000000,114.000000,121.000000,95.830000,10.000000,1.000000,97.932500,0.000000,133.000000,2023.000000
max,2267.000000,426.000000,1616.000000,228.030000,25.000000,1.000000,261.220000,1.000000,430.000000,2024.000000

In [44]:
df.duplicated().sum()

np.int64(0)

In [45]:
df['year'] = pd.to_datetime(df['Date']).dt.year
df['month'] = pd.to_datetime(df['Date']).dt.month_name()
df

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Price,Discount,Weather Condition,Promotion,Competitor Pricing,Seasonality,Epidemic,Demand,year,month
0,1/1/2022,S001,P0001,Electronics,North,195,102,252,72.72,5,Snowy,0,85.73,Winter,0,115,2022,January
1,1/1/2022,S001,P0002,Clothing,North,117,117,249,80.16,15,Snowy,1,92.02,Winter,0,229,2022,January
2,1/1/2022,S001,P0003,Clothing,North,247,114,612,62.94,10,Snowy,1,60.08,Winter,0,157,2022,January
3,1/1/2022,S001,P0004,Electronics,North,139,45,102,87.63,10,Snowy,0,85.19,Winter,0,52,2022,January
4,1/1/2022,S001,P0005,Groceries,North,152,65,271,54.41,0,Snowy,0,51.63,Winter,0,59,2022,January
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75995,1/30/2024,S005,P0016,Toys,North,233,63,0,29.80,5,Snowy,0,32.23,Winter,0,64,2024,January
75996,1/30/2024,S005,P0017,Toys,North,137,115,141,42.92,5,Snowy,0,40.73,Winter,0,137,2024,January
75997,1/30/2024,S005,P0018,Clothing,North,197,44,0,17.81,10,Snowy,0,19.41,Winter,0,68,2024,January
75998,1/30/2024,S005,P0019,Furniture,North,125,58,0,151.72,0,Snowy,0,143.71,Winter,0,84,2024,January
75999,1/30/2024,S005,P0020,Toys,North,126,63,59,25.78,10,Snowy,0,29.32,Winter,0,73,2024,January

In [46]:
print(df['month'].value_counts())
print(df['year'].value_counts())

month
January      9200
March        6200
May          6200
July         6200
August       6200
October      6200
December     6200
April        6000
June         6000
September    6000
November     6000
February     5600
Name: count, dtype: int64
year
2022    36500
2023    36500
2024     3000
Name: count, dtype: int64

In [ ]:
df.